<?php

return [
    'hard_delete' => env('APP_ENTITY_HARD_DELETE', 30),
    'logs' => env('APP_ENTITY_FULL_LOGS', 30),
    'logs_delete' => env('APP_ENTITY_LOGS_DELETE', 365),

    'ids' => [
        'character' => 1,
        'family' => 2,
        'location' => 3,
        'organisation' => 4,
        'item' => 5,
        'note' => 6,
        'event' => 7,
        'calendar' => 8,
        'race' => 9,
        'quest' => 10,
        'journal' => 11,
        'tag' => 12,
        'dice_roll' => 13,
        'conversation' => 14,
        'attribute_template' => 15,
        'ability' => 16,
        'map' => 17,
        'timeline' => 18,
        'bookmark' => 19,
        'creature' => 20,
    ],

    'classes' => [
        'ability' => 'App\Models\Ability',
        'character' => 'App\Models\Character',
        'calendar' => 'App\Models\Calendar',
        'conversation' => 'App\Models\Conversation',
        'creature' => 'App\Models\Creature',
        'event' => 'App\Models\Event',
        'family' => 'App\Models\Family',
        'item' => 'App\Models\Item',
        'journal' => 'App\Models\Journal',
        'location' => 'App\Models\Location',
        'map' => 'App\Models\Map',
        'note' => 'App\Models\Note',
        'organisation' => 'App\Models\Organisation',
        'quest' => 'App\Models\Quest',
        'race' => 'App\Models\Race',
        'tag' => 'App\Models\Tag',
        'timeline' => 'App\Models\Timeline',
        'attribute_template' => 'App\Models\AttributeTemplate',
        'dice_roll' => 'App\Models\DiceRoll',
        'bookmark' => 'App\Models\Bookmark',
        'relation' => 'App\Models\Relation',
    ],

    'classes-plural' => [
        'abilities' => 'App\Models\Ability',
        'characters' => 'App\Models\Character',
        'calendars' => 'App\Models\Calendar',
        'conversations' => 'App\Models\Conversation',
        'creatures' => 'App\Models\Creature',
        'events' => 'App\Models\Event',
        'families' => 'App\Models\Family',
        'items' => 'App\Models\Item',
        'journals' => 'App\Models\Journal',
        'locations' => 'App\Models\Location',
        'maps' => 'App\Models\Map',
        'notes' => 'App\Models\Note',
        'organisations' => 'App\Models\Organisation',
        'quests' => 'App\Models\Quest',
        'races' => 'App\Models\Race',
        'tags' => 'App\Models\Tag',
        'timelines' => 'App\Models\Timeline',
        'attribute_templates' => 'App\Models\AttributeTemplate',
        'dice_rolls' => 'App\Models\DiceRoll',
        'bookmarks' => 'App\Models\Bookmark',
        'relations' => 'App\Models\Relation',
    ],

    'icons' => [
        'character' => 'fa-solid fa-user',
        'family' => 'fa-solid fa-people-roof',
        'location' => 'fa-solid fa-circle-location-arrow',
        'organisation' => 'fa-solid fa-sitemap',
        'item' => 'fa-solid fa-gem',
        'note' => 'fa-solid fa-book-open',
        'event' => 'fa-solid fa-cake-candles',
        'calendar' => 'fa-solid fa-calendar',
        'race' => 'fa-solid fa-image-portrait',
        'quest' => 'fa-solid fa-sign-hanging',
        'journal' => 'fa-solid fa-scroll',
        'tag' => 'fa-solid fa-tags',
        'dice_roll' => 'fa-solid fa-dice',
        'conversation' => 'fa-solid fa-comments',
        'attribute_template' => 'fa-solid fa-file-export',
        'ability' => 'fa-solid fa-fire',
        'map' => 'fa-solid fa-map',
        'timeline' => 'fa-solid fa-timeline',
        'bookmark' => 'fa-solid fa-bookmark',
        'creature' => 'fa-solid fa-deer',
    ]
];
